logging:
  level:
    ROOT: INFO
    com.davin.framework.queue: DEBUG
    com.davin.service: DEBUG
  file:
    path: C:\Users\davin.bao\logs
server:
  port: 8099

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

queue:
  type: rabbitmq